### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by nextrealm** [cocos-creator/tutorial-blackjack#3]
[db-task][deep-query] Exception  TypeError: Cannot read property 'assetType' of null
    at i.Tasks.deepQuery (...CocosCreator\resources\app.asar\asset-db\lib\tasks.js:1:11192)
    at ...CocosCreator\resources\app.asar\asset-db\index.js:1:1671
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:945:13
    at Immediate.q.process [as _onImmediate] (...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:913:25)
    at processImmediate [as _immediateCallback] (timers.js:374:17)

[db-task][query-metas] Exception  TypeError: Cannot read property 'assetType' of null
    at i.Tasks.queryMetas (...CocosCreator\resources\app.asar\asset-db\lib\tasks.js:1:11851)
    at ...CocosCreator\resources\app.asar\asset-db\index.js:1:1671
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:945:13
    at Object.q.process (...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:913:25)
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:873:19
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:44:16
    at i.<anonymous> (...CocosCreator\resources\app.asar\asset-db\index.js:1:1309)
    at i.Tasks.queryMetas (...CocosCreator\resources\app.asar\asset-db\lib\tasks.js:1:11887)
    at ...CocosCreator\resources\app.asar\asset-db\index.js:1:1671
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:945:13

Exception  Error: Callback was already called.
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:43:36
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:694:17
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:173:37
    at ...CocosCreator\resources\app.asar\editor\core\preview-server.js:1:2118
    at ...CocosCreator\resources\app.asar\editor\core\gulp-build.js:1:284
    at Object.callback (...CocosCreator\resources\app.asar\asset-db\lib\interface.js:1:3696)
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:868:35
    at _arrayEach (...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:91:13)
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:867:17
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:44:16

[db-task][query-metas] Exception  TypeError: Cannot read property 'assetType' of null
    at i.Tasks.queryMetas (...CocosCreator\resources\app.asar\asset-db\lib\tasks.js:1:11851)
    at ...CocosCreator\resources\app.asar\asset-db\index.js:1:1671
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:945:13
    at Object.q.process (...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:913:25)
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:873:19
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:44:16
    at i.<anonymous> (...CocosCreator\resources\app.asar\asset-db\index.js:1:1309)
    at i.Tasks.queryMetas (...CocosCreator\resources\app.asar\asset-db\lib\tasks.js:1:11887)
    at ...CocosCreator\resources\app.asar\asset-db\index.js:1:1671
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:945:13

Exception  Error: Callback was already called.
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:43:36
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:694:17
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:173:37
    at ...CocosCreator\resources\app.asar\editor\core\preview-server.js:1:2118
    at ...CocosCreator\resources\app.asar\editor\core\gulp-build.js:1:284
    at Object.callback (...CocosCreator\resources\app.asar\asset-db\lib\interface.js:1:3696)
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:868:35
    at _arrayEach (...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:91:13)
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:867:17
    at ...CocosCreator\resources\app.asar\node_modules\async\lib\async.js:44:16

getComponent: Type must be non-nil
    at cc_Node.cc.Class.getComponent (...CocosCreator\resources\app.asar\engine\cocos2d\core\CCNode.js:450:16)
    at editor-scene.Editor.registerPanel.scene:query-node-info (file:///D:/Downloads/CocosCreator/resources/app.asar/editor/builtin/scene/panel/scene.js:1:6239)
    at EventEmitter.<anonymous> (...CocosCreator\resources\app.asar\editor-framework\lib\renderer\editor-panel.js:1:728)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (...CocosCreator\resources\app.asar\editor-framework\lib\main\editor-init.js:1:3072)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter._sendToCore (...CocosCreator\resources\app.asar\editor-framework\lib\main\ipc-init.js:1:446)
    at EventEmitter.<anonymous> (...CocosCreator\resources\app.asar\editor-framework\lib\main\ipc-init.js:1:892)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (...CocosCreator\resources\atom.asar\browser\api\lib\web-contents.js:87:23)
    at emitTwo (events.js:87:13)

**Comment by yaxinhoo** [comment]
i got the same error as u.
