### ISSUE TITLE
Cannot open project.

### ISSUE THREAD

**Issue by truonguit2010** [cocos-creator/tutorial-blackjack#4]
I cannot import this project to Cocos Creator. Please give me a hand. Thank you.

```
[db-task][deep-query] Exception  TypeError: Cannot read property 'assetType' of null
    at i.Tasks.deepQuery (/Applications/CocosCreator.app/Contents/Resources/app.asar/asset-db/lib/tasks.js:1:11192)
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/asset-db/index.js:1:1671
    at /Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:945:13
    at Immediate.q.process [as _onImmediate] (/Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/async/lib/async.js:913:25)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

**Comment by yaxinhoo** [comment]
i got the same error as u .
